library(org.Hs.eg.db) 
library(stringr)
library(ggplot2)
library(clusterProfiler)
geneList <- read.table("genelist.txt", header=TRUE)
geneID <- bitr(as.character(geneList$gene_name),fromType="SYMBOL",toType="ENTREZID",OrgDb=org.Hs.eg.db)
KEGGenrich <- enrichKEGG(geneID$ENTREZID,organism="hsa", keyType = "kegg", pvalueCutoff = 1, qvalueCutoff = 1, minGSSize = 10, maxGSSize = 500, use_internal_data=TRUE)
KEGGenrich <- setReadable(KEGGenrich, OrgDb = "org.Hs.eg.db", keyType="ENTREZID")
write.table(file="KEGG.genelist.txt", KEGGenrich, sep="\t", row.names = FALSE, quote = FALSE)